//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoyeoZoom.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: http://tempuri.org/ 네임스페이스의 요소 이름 filename이(가) "nillable"로 표시되지 않았으므로 메시지 계약을 생성합니다.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFile", ReplyAction="*")]
        BoyeoZoom.ServiceReference1.GetFileResponse GetFile(BoyeoZoom.ServiceReference1.GetFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFile", ReplyAction="*")]
        System.Threading.Tasks.Task<BoyeoZoom.ServiceReference1.GetFileResponse> GetFileAsync(BoyeoZoom.ServiceReference1.GetFileRequest request);
        
        // CODEGEN: http://tempuri.org/ 네임스페이스의 요소 이름 buffer이(가) "nillable"로 표시되지 않았으므로 메시지 계약을 생성합니다.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PutFile", ReplyAction="*")]
        BoyeoZoom.ServiceReference1.PutFileResponse PutFile(BoyeoZoom.ServiceReference1.PutFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PutFile", ReplyAction="*")]
        System.Threading.Tasks.Task<BoyeoZoom.ServiceReference1.PutFileResponse> PutFileAsync(BoyeoZoom.ServiceReference1.PutFileRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFile", Namespace="http://tempuri.org/", Order=0)]
        public BoyeoZoom.ServiceReference1.GetFileRequestBody Body;
        
        public GetFileRequest() {
        }
        
        public GetFileRequest(BoyeoZoom.ServiceReference1.GetFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string filename;
        
        public GetFileRequestBody() {
        }
        
        public GetFileRequestBody(string filename) {
            this.filename = filename;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public BoyeoZoom.ServiceReference1.GetFileResponseBody Body;
        
        public GetFileResponse() {
        }
        
        public GetFileResponse(BoyeoZoom.ServiceReference1.GetFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] GetFileResult;
        
        public GetFileResponseBody() {
        }
        
        public GetFileResponseBody(byte[] GetFileResult) {
            this.GetFileResult = GetFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PutFile", Namespace="http://tempuri.org/", Order=0)]
        public BoyeoZoom.ServiceReference1.PutFileRequestBody Body;
        
        public PutFileRequest() {
        }
        
        public PutFileRequest(BoyeoZoom.ServiceReference1.PutFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PutFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] buffer;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string filename;
        
        public PutFileRequestBody() {
        }
        
        public PutFileRequestBody(byte[] buffer, string filename) {
            this.buffer = buffer;
            this.filename = filename;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PutFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public BoyeoZoom.ServiceReference1.PutFileResponseBody Body;
        
        public PutFileResponse() {
        }
        
        public PutFileResponse(BoyeoZoom.ServiceReference1.PutFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PutFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement PutFileResult;
        
        public PutFileResponseBody() {
        }
        
        public PutFileResponseBody(System.Xml.Linq.XElement PutFileResult) {
            this.PutFileResult = PutFileResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : BoyeoZoom.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<BoyeoZoom.ServiceReference1.WebService1Soap>, BoyeoZoom.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BoyeoZoom.ServiceReference1.GetFileResponse BoyeoZoom.ServiceReference1.WebService1Soap.GetFile(BoyeoZoom.ServiceReference1.GetFileRequest request) {
            return base.Channel.GetFile(request);
        }
        
        public byte[] GetFile(string filename) {
            BoyeoZoom.ServiceReference1.GetFileRequest inValue = new BoyeoZoom.ServiceReference1.GetFileRequest();
            inValue.Body = new BoyeoZoom.ServiceReference1.GetFileRequestBody();
            inValue.Body.filename = filename;
            BoyeoZoom.ServiceReference1.GetFileResponse retVal = ((BoyeoZoom.ServiceReference1.WebService1Soap)(this)).GetFile(inValue);
            return retVal.Body.GetFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BoyeoZoom.ServiceReference1.GetFileResponse> BoyeoZoom.ServiceReference1.WebService1Soap.GetFileAsync(BoyeoZoom.ServiceReference1.GetFileRequest request) {
            return base.Channel.GetFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<BoyeoZoom.ServiceReference1.GetFileResponse> GetFileAsync(string filename) {
            BoyeoZoom.ServiceReference1.GetFileRequest inValue = new BoyeoZoom.ServiceReference1.GetFileRequest();
            inValue.Body = new BoyeoZoom.ServiceReference1.GetFileRequestBody();
            inValue.Body.filename = filename;
            return ((BoyeoZoom.ServiceReference1.WebService1Soap)(this)).GetFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BoyeoZoom.ServiceReference1.PutFileResponse BoyeoZoom.ServiceReference1.WebService1Soap.PutFile(BoyeoZoom.ServiceReference1.PutFileRequest request) {
            return base.Channel.PutFile(request);
        }
        
        public System.Xml.Linq.XElement PutFile(byte[] buffer, string filename) {
            BoyeoZoom.ServiceReference1.PutFileRequest inValue = new BoyeoZoom.ServiceReference1.PutFileRequest();
            inValue.Body = new BoyeoZoom.ServiceReference1.PutFileRequestBody();
            inValue.Body.buffer = buffer;
            inValue.Body.filename = filename;
            BoyeoZoom.ServiceReference1.PutFileResponse retVal = ((BoyeoZoom.ServiceReference1.WebService1Soap)(this)).PutFile(inValue);
            return retVal.Body.PutFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BoyeoZoom.ServiceReference1.PutFileResponse> BoyeoZoom.ServiceReference1.WebService1Soap.PutFileAsync(BoyeoZoom.ServiceReference1.PutFileRequest request) {
            return base.Channel.PutFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<BoyeoZoom.ServiceReference1.PutFileResponse> PutFileAsync(byte[] buffer, string filename) {
            BoyeoZoom.ServiceReference1.PutFileRequest inValue = new BoyeoZoom.ServiceReference1.PutFileRequest();
            inValue.Body = new BoyeoZoom.ServiceReference1.PutFileRequestBody();
            inValue.Body.buffer = buffer;
            inValue.Body.filename = filename;
            return ((BoyeoZoom.ServiceReference1.WebService1Soap)(this)).PutFileAsync(inValue);
        }
    }
}
